name: CI

on:
  push:
  pull_request:

jobs:
  spec:
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
      - name: Install packages
        run: sudo apt-get update -y && sudo apt-get install -y libunibilium-dev ncurses-term libreadline-dev
      - name: Install dependencies
        run: shards update
      - name: Run specs
        run: crystal spec
